import type { WarehouseData } from "@/lib/local/types";

const now = new Date().toISOString();
const today = new Date().toISOString().slice(0, 10);

export const initialWarehouseData: WarehouseData = {
  suppliers: [
    {
      id: "supplier-abc",
      name: "Nhà cung cấp Gạch ABC",
      phone: "0901000001",
      address: "KCN Tân Tạo, TP.HCM",
      contactPerson: "Anh Minh",
      note: "Nguồn hàng chính",
      createdAt: now,
    },
    {
      id: "supplier-xyz",
      name: "Nhà cung cấp Gạch XYZ",
      phone: "0901000002",
      address: "KCN Sóng Thần, Bình Dương",
      contactPerson: "Chị Hạnh",
      note: "Gạch cao cấp",
      createdAt: now,
    },
  ],
  customers: [
    {
      id: "customer-a",
      name: "Khách Nguyễn Văn A",
      phone: "0912000001",
      address: "Quận 8, TP.HCM",
      customerGroup: "Bán lẻ",
      note: "Khách mua thường xuyên",
      createdAt: now,
    },
    {
      id: "customer-b",
      name: "Khách Trần Văn B",
      phone: "0912000002",
      address: "Biên Hòa, Đồng Nai",
      customerGroup: "Đại lý",
      note: "Ưu tiên giao nhanh",
      createdAt: now,
    },
  ],
  products: [
    {
      id: "product-6060-a01",
      code: "G6060-A01",
      name: "Gạch bóng kính 60x60 A01",
      category: "Gạch lát nền",
      size: "60x60",
      unit: "thùng",
      piecesPerBox: 4,
      sqmPerBox: 1.44,
      importPrice: 120000,
      salePrice: 150000,
      supplierId: "supplier-abc",
      minStock: 20,
      isActive: true,
      imageUrl: "",
      note: "Hàng bán chạy",
      createdAt: now,
    },
    {
      id: "product-8080-b01",
      code: "G8080-B01",
      name: "Gạch 80x80 B01",
      category: "Gạch lát nền",
      size: "80x80",
      unit: "thùng",
      piecesPerBox: 3,
      sqmPerBox: 1.92,
      importPrice: 210000,
      salePrice: 260000,
      supplierId: "supplier-xyz",
      minStock: 15,
      isActive: true,
      imageUrl: "",
      note: "Dòng cao cấp",
      createdAt: now,
    },
    {
      id: "product-3060-c01",
      code: "G3060-C01",
      name: "Gạch 30x60 C01",
      category: "Gạch ốp tường",
      size: "30x60",
      unit: "thùng",
      piecesPerBox: 8,
      sqmPerBox: 1.44,
      importPrice: 95000,
      salePrice: 125000,
      supplierId: "supplier-abc",
      minStock: 25,
      isActive: true,
      imageUrl: "",
      note: "Ốp nhà tắm",
      createdAt: now,
    },
  ],
  purchases: [
    {
      id: "purchase-0001",
      code: "PO-0001",
      supplierId: "supplier-abc",
      orderDate: today,
      productId: "product-6060-a01",
      quantity: 100,
      unitPrice: 120000,
      totalAmount: 12000000,
      paidAmount: 8000000,
      debtAmount: 4000000,
      paymentMethod: "Chuyển khoản",
      status: "confirmed",
      note: "Dữ liệu mẫu nhập đầu kỳ",
      createdAt: now,
    },
  ],
  sales: [
    {
      id: "sale-0001",
      code: "SO-0001",
      customerId: "customer-a",
      orderDate: today,
      productId: "product-6060-a01",
      quantity: 12,
      unitPrice: 150000,
      discountAmount: 0,
      shippingFee: 100000,
      subtotalAmount: 1800000,
      totalAmount: 1900000,
      paidAmount: 1000000,
      debtAmount: 900000,
      paymentMethod: "Tiền mặt",
      deliveryStatus: "delivered",
      paymentStatus: "partial",
      status: "completed",
      note: "Dữ liệu mẫu bán hàng",
      createdAt: now,
    },
  ],
  stockMovements: [
    {
      id: "movement-po-0001",
      productId: "product-6060-a01",
      movementDate: today,
      quantity: 100,
      movementType: "purchase",
      referenceType: "purchase_order",
      referenceId: "purchase-0001",
      note: "Nhập PO-0001",
      createdAt: now,
    },
    {
      id: "movement-so-0001",
      productId: "product-6060-a01",
      movementDate: today,
      quantity: -12,
      movementType: "sale",
      referenceType: "sales_order",
      referenceId: "sale-0001",
      note: "Bán SO-0001",
      createdAt: now,
    },
  ],
  payments: [
    {
      id: "payment-po-0001",
      paymentDate: today,
      direction: "out",
      partyType: "supplier",
      supplierId: "supplier-abc",
      referenceType: "purchase_order",
      referenceId: "purchase-0001",
      amount: 8000000,
      method: "Chuyển khoản",
      note: "Trả NCC PO-0001",
      createdAt: now,
    },
    {
      id: "payment-so-0001",
      paymentDate: today,
      direction: "in",
      partyType: "customer",
      customerId: "customer-a",
      referenceType: "sales_order",
      referenceId: "sale-0001",
      amount: 1000000,
      method: "Tiền mặt",
      note: "Thu khách SO-0001",
      createdAt: now,
    },
  ],
  expenses: [
    {
      id: "expense-0001",
      category: "Vận chuyển",
      amount: 250000,
      expenseDate: today,
      paymentMethod: "Tiền mặt",
      note: "Chi phí giao hàng mẫu",
      createdAt: now,
    },
  ],
  auditLogs: [
    {
      id: "audit-seed",
      time: now,
      user: "Hệ thống",
      action: "seed",
      tableName: "local_data",
      recordCode: "INIT",
      note: "Tạo dữ liệu mẫu local-first",
    },
  ],
};
