import type { WorkspaceColumn, WorkspaceStat } from "@/components/modules/workspace-page";

export type ModulePageConfig = {
  title: string;
  eyebrow: string;
  actionLabel: string;
  exportLabel?: string;
  stats: WorkspaceStat[];
  columns: WorkspaceColumn[];
  searchPlaceholder: string;
  emptyLabel: string;
  statusFilters?: string[];
};

export const modulePages: Record<string, ModulePageConfig> = {
  sales: {
    title: "Bán hàng",
    eyebrow: "Sổ bán hàng",
    actionLabel: "Tạo đơn",
    stats: [
      { label: "Đơn hôm nay", value: "0", tone: "cyan" },
      { label: "Doanh thu hôm nay", value: "0 đ", tone: "green" },
      { label: "Khách còn nợ", value: "0 đ", tone: "amber" },
      { label: "Chờ giao", value: "0", tone: "slate" },
    ],
    columns: [
      { key: "code", label: "Mã đơn" },
      { key: "date", label: "Ngày bán" },
      { key: "customer", label: "Khách hàng" },
      { key: "items", label: "Sản phẩm" },
      { key: "total", label: "Tổng tiền", align: "right" },
      { key: "paid", label: "Đã trả", align: "right" },
      { key: "status", label: "Trạng thái" },
    ],
    searchPlaceholder: "Tìm mã đơn, khách hàng, số điện thoại",
    emptyLabel: "Chưa có đơn bán hàng",
    statusFilters: ["Tất cả", "Nháp", "Đã xác nhận", "Đang giao", "Còn nợ"],
  },
  purchases: {
    title: "Nhập hàng",
    eyebrow: "Phiếu nhập kho",
    actionLabel: "Tạo phiếu nhập",
    stats: [
      { label: "Phiếu hôm nay", value: "0", tone: "cyan" },
      { label: "Giá trị nhập", value: "0 đ", tone: "green" },
      { label: "Nợ nhà cung cấp", value: "0 đ", tone: "amber" },
      { label: "Chờ xác nhận", value: "0", tone: "slate" },
    ],
    columns: [
      { key: "code", label: "Mã phiếu" },
      { key: "date", label: "Ngày nhập" },
      { key: "supplier", label: "Nhà cung cấp" },
      { key: "items", label: "Sản phẩm" },
      { key: "total", label: "Tổng tiền", align: "right" },
      { key: "paid", label: "Đã trả", align: "right" },
      { key: "status", label: "Trạng thái" },
    ],
    searchPlaceholder: "Tìm mã phiếu, nhà cung cấp",
    emptyLabel: "Chưa có phiếu nhập kho",
    statusFilters: ["Tất cả", "Nháp", "Đã xác nhận", "Còn nợ"],
  },
  inventory: {
    title: "Tồn kho",
    eyebrow: "Kho realtime",
    actionLabel: "Điều chỉnh",
    stats: [
      { label: "Mã hàng", value: "0", tone: "cyan" },
      { label: "Giá trị tồn", value: "0 đ", tone: "green" },
      { label: "Sắp hết", value: "0", tone: "amber" },
      { label: "Hết hàng", value: "0", tone: "red" },
    ],
    columns: [
      { key: "image", label: "Ảnh", align: "center" },
      { key: "code", label: "Mã hàng" },
      { key: "name", label: "Tên hàng" },
      { key: "size", label: "Kích thước" },
      { key: "stock", label: "Tồn thùng", align: "right" },
      { key: "sqm", label: "Tồn m2", align: "right" },
      { key: "value", label: "Giá trị tồn", align: "right" },
      { key: "status", label: "Trạng thái" },
    ],
    searchPlaceholder: "Tìm mã hàng, tên gạch, kích thước",
    emptyLabel: "Chưa có dữ liệu tồn kho",
    statusFilters: ["Tất cả", "Sắp hết", "Hết hàng", "Đang bán", "Ngừng bán"],
  },
  "customer-debts": {
    title: "Công nợ khách hàng",
    eyebrow: "Sổ phải thu",
    actionLabel: "Ghi nhận thu",
    stats: [
      { label: "Tổng phải thu", value: "0 đ", tone: "amber" },
      { label: "Khách còn nợ", value: "0", tone: "cyan" },
      { label: "Nợ quá hạn", value: "0 đ", tone: "red" },
      { label: "Thu hôm nay", value: "0 đ", tone: "green" },
    ],
    columns: [
      { key: "customer", label: "Khách hàng" },
      { key: "phone", label: "Số điện thoại" },
      { key: "debtDate", label: "Ngày phát sinh" },
      { key: "lastPaymentDate", label: "Trả gần nhất" },
      { key: "bought", label: "Đã mua", align: "right" },
      { key: "paid", label: "Đã trả", align: "right" },
      { key: "debt", label: "Còn nợ", align: "right" },
      { key: "status", label: "Trạng thái" },
    ],
    searchPlaceholder: "Tìm khách hàng, số điện thoại",
    emptyLabel: "Chưa có công nợ khách hàng",
    statusFilters: ["Tất cả", "Còn nợ", "Quá hạn", "Đã tất toán"],
  },
  "supplier-debts": {
    title: "Công nợ nhà cung cấp",
    eyebrow: "Sổ phải trả",
    actionLabel: "Ghi nhận trả",
    stats: [
      { label: "Tổng phải trả", value: "0 đ", tone: "amber" },
      { label: "Nhà cung cấp còn nợ", value: "0", tone: "cyan" },
      { label: "Quá hạn", value: "0 đ", tone: "red" },
      { label: "Đã trả hôm nay", value: "0 đ", tone: "green" },
    ],
    columns: [
      { key: "supplier", label: "Nhà cung cấp" },
      { key: "contact", label: "Liên hệ" },
      { key: "debtDate", label: "Ngày phát sinh" },
      { key: "lastPaymentDate", label: "Trả gần nhất" },
      { key: "imported", label: "Đã nhập", align: "right" },
      { key: "paid", label: "Đã trả", align: "right" },
      { key: "debt", label: "Còn nợ", align: "right" },
      { key: "status", label: "Trạng thái" },
    ],
    searchPlaceholder: "Tìm nhà cung cấp, người liên hệ",
    emptyLabel: "Chưa có công nợ nhà cung cấp",
    statusFilters: ["Tất cả", "Còn nợ", "Quá hạn", "Đã tất toán"],
  },
  cashflow: {
    title: "Thu chi",
    eyebrow: "Sổ quỹ",
    actionLabel: "Thêm giao dịch",
    stats: [
      { label: "Tổng thu", value: "0 đ", tone: "green" },
      { label: "Tổng chi", value: "0 đ", tone: "red" },
      { label: "Chênh lệch", value: "0 đ", tone: "cyan" },
      { label: "Giao dịch hôm nay", value: "0", tone: "slate" },
    ],
    columns: [
      { key: "date", label: "Ngày" },
      { key: "type", label: "Loại" },
      { key: "category", label: "Danh mục" },
      { key: "amount", label: "Số tiền", align: "right" },
      { key: "method", label: "Thanh toán" },
      { key: "createdBy", label: "Người tạo" },
    ],
    searchPlaceholder: "Tìm giao dịch, ghi chú, người nhận",
    emptyLabel: "Chưa có giao dịch thu chi",
    statusFilters: ["Tất cả", "Thu", "Chi", "Tiền mặt", "Chuyển khoản"],
  },
  customers: {
    title: "Khách hàng",
    eyebrow: "Danh mục khách hàng",
    actionLabel: "Thêm khách",
    stats: [
      { label: "Tổng khách", value: "0", tone: "cyan" },
      { label: "Đang còn nợ", value: "0", tone: "amber" },
      { label: "Mua trong tháng", value: "0", tone: "green" },
      { label: "Ngừng giao dịch", value: "0", tone: "slate" },
    ],
    columns: [
      { key: "name", label: "Tên khách" },
      { key: "phone", label: "Số điện thoại" },
      { key: "address", label: "Địa chỉ" },
      { key: "group", label: "Nhóm" },
      { key: "total", label: "Tổng mua", align: "right" },
      { key: "debt", label: "Còn nợ", align: "right" },
    ],
    searchPlaceholder: "Tìm tên khách, số điện thoại, địa chỉ",
    emptyLabel: "Chưa có khách hàng",
    statusFilters: ["Tất cả", "Có công nợ", "Không công nợ", "Mua trong tháng"],
  },
  suppliers: {
    title: "Nhà cung cấp",
    eyebrow: "Danh mục nhà cung cấp",
    actionLabel: "Thêm NCC",
    stats: [
      { label: "Tổng NCC", value: "0", tone: "cyan" },
      { label: "Đang còn nợ", value: "0", tone: "amber" },
      { label: "Nhập trong tháng", value: "0", tone: "green" },
      { label: "Tạm ngưng", value: "0", tone: "slate" },
    ],
    columns: [
      { key: "name", label: "Tên NCC" },
      { key: "phone", label: "Số điện thoại" },
      { key: "contact", label: "Người liên hệ" },
      { key: "address", label: "Địa chỉ" },
      { key: "imported", label: "Tổng nhập", align: "right" },
      { key: "debt", label: "Còn nợ", align: "right" },
    ],
    searchPlaceholder: "Tìm nhà cung cấp, số điện thoại",
    emptyLabel: "Chưa có nhà cung cấp",
    statusFilters: ["Tất cả", "Có công nợ", "Không công nợ", "Nhập trong tháng"],
  },
  products: {
    title: "Sản phẩm gạch",
    eyebrow: "Danh mục hàng hóa",
    actionLabel: "Thêm sản phẩm",
    stats: [
      { label: "Mã đang bán", value: "0", tone: "cyan" },
      { label: "Giá trị tồn", value: "0 đ", tone: "green" },
      { label: "Sắp hết", value: "0", tone: "amber" },
      { label: "Ngừng bán", value: "0", tone: "slate" },
    ],
    columns: [
      { key: "image", label: "Ảnh", align: "center" },
      { key: "code", label: "Mã hàng" },
      { key: "name", label: "Tên hàng" },
      { key: "category", label: "Loại" },
      { key: "size", label: "Kích thước" },
      { key: "unit", label: "Đơn vị" },
      { key: "salePrice", label: "Giá bán", align: "right" },
      { key: "status", label: "Trạng thái" },
    ],
    searchPlaceholder: "Tìm mã hàng, tên hàng, kích thước",
    emptyLabel: "Chưa có sản phẩm gạch",
    statusFilters: ["Tất cả", "Đang bán", "Ngừng bán", "Sắp hết"],
  },
  reports: {
    title: "Báo cáo",
    eyebrow: "Tổng hợp",
    actionLabel: "Tạo báo cáo",
    exportLabel: "Xuất Excel",
    stats: [
      { label: "Doanh thu", value: "0 đ", tone: "green" },
      { label: "Giá vốn", value: "0 đ", tone: "amber" },
      { label: "Chi phí", value: "0 đ", tone: "red" },
      { label: "Lãi tạm tính", value: "0 đ", tone: "cyan" },
    ],
    columns: [
      { key: "name", label: "Báo cáo" },
      { key: "period", label: "Kỳ dữ liệu" },
      { key: "revenue", label: "Doanh thu", align: "right" },
      { key: "cost", label: "Chi phí", align: "right" },
      { key: "profit", label: "Lãi tạm tính", align: "right" },
      { key: "status", label: "Trạng thái" },
    ],
    searchPlaceholder: "Tìm báo cáo, khách hàng, sản phẩm",
    emptyLabel: "Chưa có dữ liệu báo cáo",
    statusFilters: ["Bán hàng", "Nhập hàng", "Tồn kho", "Công nợ", "Thu chi"],
  },
  "audit-logs": {
    title: "Nhật ký thao tác",
    eyebrow: "Audit log",
    actionLabel: "Xuất log",
    stats: [
      { label: "Thao tác hôm nay", value: "0", tone: "cyan" },
      { label: "Tạo mới", value: "0", tone: "green" },
      { label: "Cập nhật", value: "0", tone: "amber" },
      { label: "Hủy phiếu", value: "0", tone: "red" },
    ],
    columns: [
      { key: "time", label: "Thời gian" },
      { key: "user", label: "Người thao tác" },
      { key: "action", label: "Hành động" },
      { key: "table", label: "Bảng" },
      { key: "record", label: "Mã ghi nhận" },
      { key: "note", label: "Ghi chú" },
    ],
    searchPlaceholder: "Tìm người thao tác, mã phiếu, bảng dữ liệu",
    emptyLabel: "Chưa có nhật ký thao tác",
    statusFilters: ["Tất cả", "Tạo mới", "Cập nhật", "Hủy phiếu", "Đăng nhập"],
  },
  users: {
    title: "Tài khoản & phân quyền",
    eyebrow: "Quản trị người dùng",
    actionLabel: "Mời người dùng",
    stats: [
      { label: "Tài khoản", value: "0", tone: "cyan" },
      { label: "Admin", value: "0", tone: "green" },
      { label: "Kế toán", value: "0", tone: "amber" },
      { label: "Tạm khóa", value: "0", tone: "red" },
    ],
    columns: [
      { key: "name", label: "Họ tên" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Số điện thoại" },
      { key: "role", label: "Vai trò" },
      { key: "status", label: "Trạng thái" },
      { key: "createdAt", label: "Ngày tạo" },
    ],
    searchPlaceholder: "Tìm họ tên, email, số điện thoại",
    emptyLabel: "Chưa có hồ sơ người dùng",
    statusFilters: ["Tất cả", "Admin", "Kế toán", "Người góp chung", "Nhân viên kho"],
  },
  settings: {
    title: "Cài đặt",
    eyebrow: "Hệ thống",
    actionLabel: "Lưu cấu hình",
    stats: [
      { label: "Chi nhánh", value: "1", tone: "cyan" },
      { label: "Kho", value: "1", tone: "green" },
      { label: "Khóa sổ", value: "0 kỳ", tone: "amber" },
      { label: "Tích hợp", value: "Supabase", tone: "slate" },
    ],
    columns: [
      { key: "name", label: "Thiết lập" },
      { key: "value", label: "Giá trị" },
      { key: "scope", label: "Phạm vi" },
      { key: "updatedBy", label: "Người cập nhật" },
      { key: "updatedAt", label: "Thời gian" },
      { key: "status", label: "Trạng thái" },
    ],
    searchPlaceholder: "Tìm cấu hình, khóa sổ, kho",
    emptyLabel: "Chưa có cấu hình tùy chỉnh",
    statusFilters: ["Tất cả", "Kho", "Bảo mật", "Khóa sổ", "Realtime"],
  },
};
